# @see https://jena.apache.org/documentation/geosparql/index.html
PREFIX geo: <http://www.opengis.net/ont/geosparql#>

SELECT ?subject ?object
WHERE{
    ?subject geo:sfContains ?object
} ORDER by ?object
