# sparql --data=osm-permaids.ttl --query=query-example-3.rq

PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX osmq: <https://community.openstreetmap.org/t/persistent-and-stable-identifiers/6819#>
PREFIX osmt: <https://wiki.openstreetmap.org/wiki/Key:>
PREFIX osmw: <https://wiki.openstreetmap.org/wiki/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX xpto: <https://example.org/todo-fixme/>
PREFIX wikidata: <http://www.wikidata.org/entity/>
PREFIX osmtx: <https://wiki.openstreetmap.org/wiki/Key:>

# https://jena.apache.org/documentation/geosparql/index.html
# https://jena.apache.org/documentation/geosparql/index
SELECT ?subject ?object
WHERE {
    # ?subject geo:sfContains ?subject
    # ?subject geo:sfWithin ?subject
    ?subject osmtx:is_in ?object
} ORDER by ?subject
